/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionList: typeof import('./src/components/AccordionList.vue')['default']
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    ArticleList: typeof import('./src/components/hero/ArticleList.vue')['default']
    ButtonCard: typeof import('./src/components/index/ButtonCard.vue')['default']
    NoticeBar: typeof import('./src/components/index/NoticeBar.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutPagination: typeof import('@nutui/nutui-taro')['Pagination']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    SwiperImage: typeof import('./src/components/index/SwiperImage.vue')['default']
  }
}
