/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccordionList: typeof import('./src/components/AccordionList.vue')['default']
    AnswerBox: typeof import('./src/components/pal/AnswerBox.vue')['default']
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    ButtonCard: typeof import('./src/components/index/ButtonCard.vue')['default']
    Comment: typeof import('./src/components/post/Comment.vue')['default']
    CommentInput: typeof import('./src/components/CommentInput.vue')['default']
    FixedButton: typeof import('./src/components/FixedButton.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutEllipsis: typeof import('@nutui/nutui-taro')['Ellipsis']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutPagination: typeof import('@nutui/nutui-taro')['Pagination']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSkeleton: typeof import('@nutui/nutui-taro')['Skeleton']
    NutSpace: typeof import('@nutui/nutui-taro')['Space']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    OptionButton: typeof import('./src/components/pal/OptionButton.vue')['default']
    PostCard: typeof import('./src/components/post/PostCard.vue')['default']
    ProgressBar: typeof import('./src/components/pal/ProgressBar.vue')['default']
    SwiperImage: typeof import('./src/components/index/SwiperImage.vue')['default']
    WordCloud: typeof import('./src/components/post/WordCloud.vue')['default']
  }
}
