spring:
  datasource:
    url: jdbc:mysql://localhost:3306/edu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    port: 465
    username: 12345678@qq.com
    password: vjycvdisrecyhi
    test-connection: true
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10s
      lettuce:
        pool:
          max-active: 100
          max-wait: 100ms
          max-idle: 3
          min-idle: 0

  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: sk-12345678910
      embedding:
        enabled: false
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8
