server:
  port: 8080

spring:
  application:
    name: edu-app
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  token-name: authorization
  timeout: 604800
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: simple-uuid
  isReadHeader: true
  isReadCookie: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '基于springboot的红星国防平台'
      paths-to-match: '/**'
      packages-to-scan: cn.org.shelly.edu.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    com.swpu: debug

thread:
  pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 50
    keep-alive-seconds: 60
